[package]
name = "problem-solving-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "week_1_a"
path = "src/week_1/A/main.rs"

[[bin]]
name = "week_1_b"
path = "src/week_1/B/main.rs"